version: '3'
services:
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_DB_PASSWORD}
      MYSQL_DATABASE: ${LOCAL_DB_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - ./db/data:/var/lib/mysql
  app:
    image: haksoo/wanted-server-dev:0.1.4
    container_name: app
    ports:
      - 80:80
    depends_on:
      - db
